### ISSUE TITLE
Add more Biolink category checks

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/universalizer#5]
At present, Biolink categories are only:
* Checked to ensure they aren't `OntologyClass`
* Assigned on a node-by-node basis through SSSOM maps

It would be preferable to do additional category verification by [getting categories with OAK](https://github.com/INCATools/ontology-access-kit/blob/bfde50a5c64ec82f7fceeb562c2151f3dd565d5d/src/oaklib/cli.py#L2504) ([see what KGX does too](https://github.com/biolink/kgx/blob/master/kgx/utils/graph_utils.py#L78))

This should be optional from the CLI.

Gotta output a list of "unmappable" nodes in order to catch those OAK may not know about.

**Comment by matentzn** [comment]
Yeah, I think this is a very good idea.

**Comment by caufieldjh** [comment]
Also need to check for existence of conflicting category assignments.
A node can have multiple categories, but not if any of them are the wrong type (like `OntologyClass`) or incompatible as per Biolink.

There may be category assignments represented as relations, and that's mostly just noise in a property graph, but it's preferable to convert them to categories and remove the redundant relations.
